---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes
- name: "install dependencies"
  become: yes
  apt:
    name: [nodejs, npm]
    state: present
- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: "create ~/web directory"
  file:
    path: ~/web
    state: directory
- name: "copy index.js"
  copy:
    src: index.js
    dest: ~/web/index.js
- name: "start web server"
  shell: |
    pm2 start ~/web/index.js -f
